name: Generate ASCII Artwork

on:
    push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Checkout repo files
          run: ls -ltra

        - name: Executing shell script
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh
        
        - name: Upload dragon file
          uses: actions/upload-artifact@v3
          with: 
            name: dragon-text-file
            path: dragon.txt

    read_job:
        needs: ascii_job
        runs-on: ubuntu-latest
        steps:
        - name: Download dragon file
          uses: actions/download-artifact@v3
          with:
            name: dragon-text-file

        - name: Verify
          run: cat dragon.txt