name: Generate ASCII Artwork

on:
    push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Alguien tenía que hacerlo." >> dragon.txt

        - name: Test File Exists
          run: grep -i "Alguien" dragon.txt

        - name: Read file
          run: cat dragon.txt

        - name: Checkout repo files
          run: ls
